apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubefirst
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://charts.kubefirst.com
    targetRevision: 2.3.5
    chart: kubefirst
    helm:
      values: |-
        global:
          kubefirstVersion: "v2.3.5"
          cloudProvider: "k3d"
          clusterId: "ocmkt0"
          clusterType: "mgmt"
          domainName: "k8s.dev.io"
          gitProvider: "github"
          installMethod: "helm"
          kubefirstClient: "<KUBEFIRST_CLIENT>"
          kubefirstTeam: "false"
          kubefirstTeamInfo: "<KUBEFIRST_TEAM_INFO>"
          useTelemetry: "true"
        kubefirst-api-ee:
          env:
            - name: IN_CLUSTER
              value: "'true'"
        kubefirst-api:
          isClusterZero: "'false'"
          env:
            - name: IN_CLUSTER
              value: "'true'"
            - name: CLUSTER_NAME
              value: "kubefirst"
            - name: ENTERPRISE_API_URL
              value: "http://kubefirst-kubefirst-api-ee.kubefirst.svc.cluster.local"
        console:
          isClusterZero: "'false'"
          domain: "k8s.dev.io"
          env:
            DISABLE_AUTH:
              value: "true"
          extraEnvSecrets:
            CLIENT_ID:
              name: kubefirst-console-secrets
              key: client_id
            SECRET_ID:
              name: kubefirst-console-secrets
              key: client_secret
          ingress:
            enabled: "true"
            hosts:
              - host: kubefirst.k8s.dev.io
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: kubefirst-tls
                hosts:
                  - kubefirst.k8s.dev.io
  destination:
    server: https://kubernetes.default.svc
    namespace: kubefirst
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
