___
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: directpv-min-io
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
___
apiVersion: v1
kind: PersistentVolume
metadata:
  name: directpv-min-io
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/fenikz/dev/data
___
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: directpv-min-io
  resources:
    requests:
      storage: 512Mi
